### ISSUE TITLE
Regex nya ke hapus  😂

### ISSUE THREAD

**Issue by ryugenxd** [fiandev/jawa-language#1]
![IMG_20221005_201547](https://user-images.githubusercontent.com/109148993/194058213-2e215b82-67b1-47b4-9ffd-16cc9c05b919.jpg)
@fiandev

**Comment by fiandev** [comment]
Udah gw fix

**Comment by fiandev** [comment]
Bug fixed

**Comment by ryugenxd** [comment]
yatta 😊
